work_dir: 'work_dir'

data:
  name: 'ParamalIDDChallenge'
  train_dir: 'dataset/train'
  test_dir: 'dataset/test'
  sample_submission_path: 'dataset/submission.csv'
  train_df_path: 'dataset/train.csv'
  params:
    idx_fold: 0
    num_folds: 5
  num_classes: 8

test:
  batch_size: 16
  best_threshold: 0.5
  min_size: [500, 500, 1000, 2000]
  tta: True

transforms:
  test:
    HorizontalFlip: False
    VerticalFlip: False
    Cutout:
      num_holes: 0
      hole_size: 25
    RandomCropScale: False
    CropSize: 0

num_workers: 2
device: 'cuda'
